server:
  port: 8081

# 'spring:' must not be indented (it starts at the beginning of the line)
spring:
  # 'datasource:' must be indented by 2 spaces under 'spring:'
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: abc@123 # IMPORTANT: Use your real password here
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates tables automatically
    show-sql: true

# These properties are for your JWT logic
jwt:
  secret: ThisIsAVeryLongAndSecureSecretKeyForYourChatApplicationPleaseChangeIt
  expiration-ms: 86400000 # 24 hours
